# Generated by Django 2.2.1 on 2019-08-08 17:03

import design.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=126, verbose_name='제목')),
                ('image', models.ImageField(upload_to=design.models.user_path)),
                ('discription', models.TextField(verbose_name='내용')),
                ('author', models.CharField(max_length=16, verbose_name='작성자')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성일')),
            ],
        ),
        migrations.DeleteModel(
            name='DesignPiece',
        ),
    ]
